"""changes to the database

Revision ID: 1255cb0a0726
Revises: 5325f7f0b459
Create Date: 2025-02-19 14:13:47.533358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1255cb0a0726'
down_revision = '5325f7f0b459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.drop_column('street')
        batch_op.drop_column('county')
        batch_op.drop_column('town')

    with op.batch_alter_table('service_providers', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_column('location')
        batch_op.drop_column('firstname')
        batch_op.drop_column('username')
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_username_key', ['username'])
        batch_op.drop_column('fullname')

    with op.batch_alter_table('service_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('town', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('county', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('street', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
