"""service table

Revision ID: 148685000fd6
Revises: 1255cb0a0726
Create Date: 2025-02-19 15:26:57.054093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148685000fd6'
down_revision = '1255cb0a0726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20055),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=20055),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
